// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Script} from "forge-std/Script.sol";
import {console2} from "forge-std/console2.sol";

import {Config, DeployConfig} from "./Config.sol";
import {Deployment, Deployed} from "./Deployment.sol";
import {DeployChecks} from "./DeployChecks.sol";

/// @title Verify
/// @notice Post-deploy verification, runnable standalone against a system this process did not deploy. It
/// reads `config/<chainId>.json` and `deployments/<chainId>.json`, asserts every wiring, ownership, timelock,
/// guardian, cap, fee, bond and pause invariant through `DeployChecks`, prints the address table, and writes
/// the Blockscout commands for re-verifying every contract.
///
/// @dev No broadcast and no state change: every call is a read, and the one write is a local file. Run it
/// after each stage of a mainnet deploy — the assertions that pass tell you exactly how far the handover got.
///
///   forge script script/Verify.s.sol:Verify --sig "run()" --rpc-url robinhood_testnet \
///     --libraries src/libraries/TickMath.sol:TickMath:0xTHE_DEPLOYED_ADDRESS
///
/// The `--libraries` flag is required for the same reason it is required to deploy: this build carries a
/// TickMath link placeholder, and `DeployChecks.assertLibrary` compares the linked address against the one
/// the deployment recorded (D-058).
contract Verify is Script {
    string internal sh;

    function run() external {
        _run(block.chainid);
    }

    /// @notice Verify a chain other than the RPC's, for reading an address book offline. The on-chain
    /// assertions only mean anything when the chain id matches the RPC.
    function runFor(uint256 chainId) external {
        _run(chainId);
    }

    function _run(uint256 chainId) internal {
        DeployConfig memory c = Config.read(chainId);
        Deployed memory d = Deployment.read(chainId);
        require(c.chainId == d.chainId, "config and deployment disagree on the chain");

        DeployChecks.assertAll(c, d);
        DeployChecks.report(c, d);

        _writeVerifyScript(c, d);
        console2.log("");
        console2.log("All assertions passed.");
        console2.log("Blockscout commands written to", _path(chainId));
    }

    // ───────────────────────────── blockscout ─────────────────────────────

    /// @dev `--guess-constructor-args` lets Blockscout recover the arguments from the creation transaction, so
    /// the address book does not have to carry them. The `--libraries` flag is not optional: the deployed
    /// bytecode of `SettlementOracle` and `WritePriceOracle` has the TickMath address linked into it, and
    /// without the same flag the recompiled bytecode will not match.
    ///
    /// Verifier URLs (SPEC §1.1 for the explorer host; the testnet path is not recorded there and was
    /// confirmed against a live Blockscout v10.2.6 instance):
    ///   4663  https://robinhoodchain.blockscout.com/api/
    ///   46630 https://explorer.testnet.chain.robinhood.com/api/
    function _writeVerifyScript(DeployConfig memory c, Deployed memory d) internal {
        sh = string.concat(
            "#!/bin/sh\n",
            "# Generated by script/Verify.s.sol. Re-verifies every contract of the ",
            c.label,
            " deployment.\n",
            "# forge script --broadcast --verify already does this during the deploy; this is the re-run.\n",
            "set -eu\n",
            'cd "$(dirname "$0")/.."\n\n',
            "CHAIN=",
            vm.toString(c.chainId),
            "\n",
            "VERIFIER=",
            c.verifier,
            "\n",
            "VERIFIER_URL=",
            c.verifierUrl,
            "\n",
            "LIBS=src/libraries/TickMath.sol:TickMath:",
            vm.toString(d.tickMath),
            "\n\n"
        );
        _core(d);
        _vaults(d);
        _token(d);
        vm.writeFile(_path(c.chainId), sh);
    }

    function _core(Deployed memory d) private {
        _add("TickMath", d.tickMath, "src/libraries/TickMath.sol:TickMath");
        _add(
            "TimelockController",
            d.timelock,
            "lib/openzeppelin-contracts/contracts/governance/TimelockController.sol:TimelockController"
        );
        _add("RiskModule", d.riskModule, "src/RiskModule.sol:RiskModule");
        _add("OptionToken", d.optionToken, "src/OptionToken.sol:OptionToken");
        _add("BondManager", d.bondManager, "src/BondManager.sol:BondManager");
        _add("FeeRouter", d.feeRouter, "src/FeeRouter.sol:FeeRouter");
        _add("AuctionHouse", d.auctionHouse, "src/AuctionHouse.sol:AuctionHouse");
        _add("CapController", d.capController, "src/CapController.sol:CapController");
        _add("SettlementOracle", d.settlementOracle, "src/SettlementOracle.sol:SettlementOracle");
    }

    function _vaults(Deployed memory d) private {
        for (uint256 i; i < d.vaults.length; ++i) {
            _add(
                string.concat("CoveredCallVault (", d.vaults[i].symbol, ")"),
                d.vaults[i].vault,
                "src/CoveredCallVault.sol:CoveredCallVault"
            );
        }
        // The mocks are recorded in `mocked` and verify the same way; they are testnet fixtures, so their
        // sources are in `src/mocks/` and Blockscout can guess their arguments too.
        for (uint256 i; i < d.vaults.length; ++i) {
            if (d.mocked.length == 0) break;
            _add(
                string.concat("MockStockToken (", d.vaults[i].symbol, ")"),
                d.vaults[i].stock,
                "src/mocks/MockStockToken.sol:MockStockToken"
            );
            _add(
                string.concat("MockAggregatorV3 (", d.vaults[i].symbol, ")"),
                d.vaults[i].feed,
                "src/mocks/MockAggregatorV3.sol:MockAggregatorV3"
            );
            _add(
                string.concat("MockUniswapV3Pool (", d.vaults[i].symbol, ")"),
                d.vaults[i].pool,
                "src/mocks/MockUniswapV3Pool.sol:MockUniswapV3Pool"
            );
        }
        if (d.mocked.length != 0) {
            _add("MockUSDG", d.usdg, "src/mocks/MockUSDG.sol:MockUSDG");
            _add("MockAggregatorV3 (USDG/USD)", d.usdgUsdFeed, "src/mocks/MockAggregatorV3.sol:MockAggregatorV3");
        }
    }

    function _token(Deployed memory d) private {
        if (d.write == address(0)) return;
        _add("WRITE", d.write, "src/WRITE.sol:WRITE");
        _add("LiquidityEscrow", d.liquidityEscrow, "src/LiquidityEscrow.sol:LiquidityEscrow");
        _add("EmissionsController", d.emissionsController, "src/EmissionsController.sol:EmissionsController");
        _add("Vesting (treasury)", d.treasuryVesting, "src/Vesting.sol:Vesting");
        _add("Vesting (team)", d.teamVesting, "src/Vesting.sol:Vesting");
        _add("PointsDistributor", d.pointsDistributor, "src/PointsDistributor.sol:PointsDistributor");
        _add("WritePriceOracle", d.writePriceOracle, "src/WritePriceOracle.sol:WritePriceOracle");
        _add("SafetyModule", d.safetyModule, "src/SafetyModule.sol:SafetyModule");
    }

    function _add(string memory label, address at, string memory target) private {
        if (at == address(0)) return;
        sh = string.concat(
            sh,
            "# ",
            label,
            "\n",
            "forge verify-contract ",
            vm.toString(at),
            " ",
            target,
            ' --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" ',
            '--libraries "$LIBS" --guess-constructor-args --watch\n\n'
        );
    }

    function _path(uint256 chainId) internal pure returns (string memory) {
        return string.concat("deployments/", vm.toString(chainId), "-verify.sh");
    }
}
