#!/bin/sh
# Generated by script/Verify.s.sol. Re-verifies every contract of the robinhood-testnet deployment.
# forge script --broadcast --verify already does this during the deploy; this is the re-run.
set -eu
cd "$(dirname "$0")/.."

CHAIN=46630
VERIFIER=blockscout
VERIFIER_URL=https://explorer.testnet.chain.robinhood.com/api/
LIBS=src/libraries/TickMath.sol:TickMath:0x80AbE3b669ecF49FA57883661A4c4F94E79B79e7

# TickMath
forge verify-contract 0x80AbE3b669ecF49FA57883661A4c4F94E79B79e7 src/libraries/TickMath.sol:TickMath --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# TimelockController
forge verify-contract 0x7055b20A990dF9e9724a9e0Fe20e8Ab91baA0899 lib/openzeppelin-contracts/contracts/governance/TimelockController.sol:TimelockController --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# RiskModule
forge verify-contract 0x8fc5FF8Ee10E8081ee6D1b0b9BA873149Aaaf007 src/RiskModule.sol:RiskModule --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# OptionToken
forge verify-contract 0x3F6a1E5f16b66354fd56C8AAA5b25927bEA6aAfC src/OptionToken.sol:OptionToken --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# BondManager
forge verify-contract 0x056E0Def113493512060ed28F5e5AD7cb04A4c6C src/BondManager.sol:BondManager --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# FeeRouter
forge verify-contract 0x8c7E78F20EE71B7B9d674ee30CC39618c8E10333 src/FeeRouter.sol:FeeRouter --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# AuctionHouse
forge verify-contract 0x2Ab9fe15E0E98067a18d804347C7b13E36503A95 src/AuctionHouse.sol:AuctionHouse --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# CapController
forge verify-contract 0x6CBb14A22a1Bd3C3FA1017d757c079D274118f81 src/CapController.sol:CapController --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# SettlementOracle
forge verify-contract 0xba214c8463F5C874c7851DCb09b01A0b2319E108 src/SettlementOracle.sol:SettlementOracle --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# CoveredCallVault (NVDA)
forge verify-contract 0xe2029A8BDF6f559E50160Eb59f1E4B4Fc7A011C5 src/CoveredCallVault.sol:CoveredCallVault --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# CoveredCallVault (SPY)
forge verify-contract 0xbAB66DC34052479eF7a97e213DA8a9948ff772E3 src/CoveredCallVault.sol:CoveredCallVault --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# MockStockToken (NVDA)
forge verify-contract 0xc2D152ebE42be2c65d86c50b410231e5271634fb src/mocks/MockStockToken.sol:MockStockToken --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# MockAggregatorV3 (NVDA)
forge verify-contract 0x2d4e84FBaE927EcF2CCc924808E593BA48F1b72F src/mocks/MockAggregatorV3.sol:MockAggregatorV3 --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# MockUniswapV3Pool (NVDA)
forge verify-contract 0x8e1CFC19D17EC56CB6C6b545596637F60376B3c9 src/mocks/MockUniswapV3Pool.sol:MockUniswapV3Pool --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# MockStockToken (SPY)
forge verify-contract 0x3c37fE477079789cA80b0F20A6585d96894f2006 src/mocks/MockStockToken.sol:MockStockToken --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# MockAggregatorV3 (SPY)
forge verify-contract 0x301dd8371eD858A77474c5506236B8EBA5F5961b src/mocks/MockAggregatorV3.sol:MockAggregatorV3 --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# MockUniswapV3Pool (SPY)
forge verify-contract 0x75671ad2E95DB072817DF949A1fD143A8C398769 src/mocks/MockUniswapV3Pool.sol:MockUniswapV3Pool --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# MockUSDG
forge verify-contract 0x640c46710A5C075292655e8602EC1D4BA844A930 src/mocks/MockUSDG.sol:MockUSDG --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# MockAggregatorV3 (USDG/USD)
forge verify-contract 0x2C51f2f94BBd847DF1Bb9cb82669B538Cbd96FDe src/mocks/MockAggregatorV3.sol:MockAggregatorV3 --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# WRITE
forge verify-contract 0x0B3D6678024Cf5063f8C0fcfe3e39354d38E71CA src/WRITE.sol:WRITE --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# LiquidityEscrow
forge verify-contract 0x5e0B4E64d1CA5718C169fB59c27BA7fA62D2F671 src/LiquidityEscrow.sol:LiquidityEscrow --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# EmissionsController
forge verify-contract 0x8C3Ff7AA63b3b688B50bDc50c3C60A88a3274a31 src/EmissionsController.sol:EmissionsController --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# Vesting (treasury)
forge verify-contract 0x27D0bC570243D6B0357C96dd2d6e1F64ad95F69D src/Vesting.sol:Vesting --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# Vesting (team)
forge verify-contract 0xa0abaa4eC77a42ceaaB065a0de2bD93dD44e5273 src/Vesting.sol:Vesting --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# PointsDistributor
forge verify-contract 0xae2E4F198fc8c29e91422E197Ffd0217Ad679712 src/PointsDistributor.sol:PointsDistributor --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# WritePriceOracle
forge verify-contract 0xfEca213236d5e21b8d38A083D4bf6694C0a970b7 src/WritePriceOracle.sol:WritePriceOracle --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# SafetyModule
forge verify-contract 0xa7f27067858593C5D87C60C9407F726fc2b48e05 src/SafetyModule.sol:SafetyModule --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

