#!/bin/sh
# Generated by script/Verify.s.sol. Re-verifies every contract of the robinhood-testnet deployment.
# forge script --broadcast --verify already does this during the deploy; this is the re-run.
set -eu
cd "$(dirname "$0")/.."

CHAIN=46630
VERIFIER=blockscout
VERIFIER_URL=https://explorer.testnet.chain.robinhood.com/api/
LIBS=src/libraries/TickMath.sol:TickMath:0x80AbE3b669ecF49FA57883661A4c4F94E79B79e7

# TickMath
forge verify-contract 0x80AbE3b669ecF49FA57883661A4c4F94E79B79e7 src/libraries/TickMath.sol:TickMath --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# TimelockController
forge verify-contract 0x183CD3640c5Cf5886F09117c7cF9B844782e9E8C lib/openzeppelin-contracts/contracts/governance/TimelockController.sol:TimelockController --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# RiskModule
forge verify-contract 0x23580d6EB623Ad8108512e6ea27ae3852F295740 src/RiskModule.sol:RiskModule --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# OptionToken
forge verify-contract 0x56009D85b2318A3B3aDbE5764f602C0F26555eA6 src/OptionToken.sol:OptionToken --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# BondManager
forge verify-contract 0x920F79DF191899934a04269B2280B2A1B2391266 src/BondManager.sol:BondManager --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# FeeRouter
forge verify-contract 0xCb3FaaD6515DF255Bc080194Eb32dA357B12775b src/FeeRouter.sol:FeeRouter --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# AuctionHouse
forge verify-contract 0xEFE287cE0761813e642B6df5D6A08637E97E9B93 src/AuctionHouse.sol:AuctionHouse --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# CapController
forge verify-contract 0xf0BeEf79C7c9AbaA07a4B18e709F613516Db0034 src/CapController.sol:CapController --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# SettlementOracle
forge verify-contract 0xc4b9C798d552105e2cE72EE6b286C0740AA1E4d1 src/SettlementOracle.sol:SettlementOracle --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# CoveredCallVault (NVDA)
forge verify-contract 0x7d873a335aD3cf8cc5A7AfEe8fA80b2d042b54E0 src/CoveredCallVault.sol:CoveredCallVault --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# CoveredCallVault (SPY)
forge verify-contract 0x7b242611B7C490BC5F571095ef511d60E89bf914 src/CoveredCallVault.sol:CoveredCallVault --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# MockStockToken (NVDA)
forge verify-contract 0xc2D152ebE42be2c65d86c50b410231e5271634fb src/mocks/MockStockToken.sol:MockStockToken --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# MockAggregatorV3 (NVDA)
forge verify-contract 0x2d4e84FBaE927EcF2CCc924808E593BA48F1b72F src/mocks/MockAggregatorV3.sol:MockAggregatorV3 --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# MockUniswapV3Pool (NVDA)
forge verify-contract 0x8e1CFC19D17EC56CB6C6b545596637F60376B3c9 src/mocks/MockUniswapV3Pool.sol:MockUniswapV3Pool --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# MockStockToken (SPY)
forge verify-contract 0x3c37fE477079789cA80b0F20A6585d96894f2006 src/mocks/MockStockToken.sol:MockStockToken --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# MockAggregatorV3 (SPY)
forge verify-contract 0x301dd8371eD858A77474c5506236B8EBA5F5961b src/mocks/MockAggregatorV3.sol:MockAggregatorV3 --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# MockUniswapV3Pool (SPY)
forge verify-contract 0x75671ad2E95DB072817DF949A1fD143A8C398769 src/mocks/MockUniswapV3Pool.sol:MockUniswapV3Pool --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# MockUSDG
forge verify-contract 0x640c46710A5C075292655e8602EC1D4BA844A930 src/mocks/MockUSDG.sol:MockUSDG --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# MockAggregatorV3 (USDG/USD)
forge verify-contract 0x2C51f2f94BBd847DF1Bb9cb82669B538Cbd96FDe src/mocks/MockAggregatorV3.sol:MockAggregatorV3 --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# WRITE
forge verify-contract 0x0651AE06f048580562571fFB7CABf49Ae06010B8 src/WRITE.sol:WRITE --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# LiquidityEscrow
forge verify-contract 0xC628235207277D0fc9404830e8131021EbD307Fa src/LiquidityEscrow.sol:LiquidityEscrow --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# EmissionsController
forge verify-contract 0x7d6d98c4dcc35c11916C34D5d63D82FC3796B4Ea src/EmissionsController.sol:EmissionsController --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# Vesting (treasury)
forge verify-contract 0xD9D4bD50f1736eE0564D80d2e3A7eEF0043270bf src/Vesting.sol:Vesting --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# Vesting (team)
forge verify-contract 0x912d806F9f4978Bd96BA39B242365f1A561A8193 src/Vesting.sol:Vesting --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# PointsDistributor
forge verify-contract 0x03580256D92367C39d816fC38686DD91ccFA6b66 src/PointsDistributor.sol:PointsDistributor --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# WritePriceOracle
forge verify-contract 0xaE21883c2401D0eb721995D2eEb48dd72FD45891 src/WritePriceOracle.sol:WritePriceOracle --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

# SafetyModule
forge verify-contract 0x37DEC60be0cd81ad9c9a5f5082A81d27779d3Ba1 src/SafetyModule.sol:SafetyModule --chain-id "$CHAIN" --verifier "$VERIFIER" --verifier-url "$VERIFIER_URL" --libraries "$LIBS" --guess-constructor-args --watch

